### ISSUE TITLE
add code

### ISSUE THREAD

**Issue by BiplabPrasad** [BiplabPrasad/beginners#2]
add new programs of various difficulty

**Comment by hraj43** [comment]
i want to work on this problem.

**Comment by hemantwasthere** [comment]
Hey,  I would like to work on this issue

**Comment by BiplabPrasad** [comment]
@harshraj438524 @hemantwasthere  you both can work on it

**Comment by hemantwasthere** [comment]
Hey @BiplabPrasad, I have opened a PR regarding this issue, Please have a look and let me know if there something to change
